enable_audio_bell no
font_size 16.0
background_opacity 1
# background_image /usr/share/backgrounds/manjaro-wallpapers-18.0/manjaro-cat.jpg 
background_color #050607
background_image_layout scaled
background_tint 0.5

clipboard_control write-clipboard write-primary read-clipboard-ask read-primary-ask
copy_on_select clipboard
mouse_map right press ungrabbed paste_from_selection
